### ISSUE TITLE
Issue getting sensor status to MQTT SERVER

### ISSUE THREAD

**Issue by FigJam23** [Wifsimster/pir-mqtt#1]
Have uploaded all lua files and have editing the config file prior device connects to network correctly but when status of GPIO2 / pin 4 changes state there is no message received by my MQTT mosquito server seems to be a issue with connecting to the mqtt service. I have tested pin status changes inside the lua upload program I'm using and get out out of 0 an 1 so I believe this proves the pin is functioning correctly . any ideas please 

-- Wifi Settings
AP = "Fakename"
PWD = "Fakepw"

-- MQTT Broker
BROKER_IP = "10.0.0.59"
BROKER_PORT = 1883

-- MQTT Settings
CLIENT_ID = "ESP8266-"..node.chipid()
ONLINE_TOPIC = "/online/"
PING_TOPIC = "/ping/"
DATA_TOPIC = "/sensors/motion/"
DEVICE_TYPE = "motion"

-- GPIO
DATA_PIN = 4 -- GPIO_2

**Comment by mydakota** [comment]
wifi_event_monitor_handle_event_cb is called
k) print(l.."   "..v.." bytes") end
> 
> WiFi connection established
IP address: 10.0.0.61
pin,mode,pullup= 4 2 0
Pin data at mode: 4 60000838, 2 0 0, fffffffe
Function platform_gpio_mode() is called. pin_mux:1610614840, func:0
PANIC: unprotected error in call to Lua API (main.lua:8: attempt to index global 'mqtt' (a nil value))
c_ÇRSöfJSúfJSjê‚ÂÇêÓïogËãÊÖOoËSÂËÏWþûsSSâÒRFþ“ëßçSçkûBoBëg×ûçËÿÃBc_ÇRSöfJSúfJSjê†ÂÇêÓï/gËãÊÖOoËSÂËÏWþûs·owu¯{u{w}{÷´k{ýWaiting for IP address...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 6
cnt 

connected with ParkwayDrive, channel 13
dhcp client start...

	wifi_event_monitor_handle_event_cb is called
Waiting for IP address...
ip:10.0.0.61,mask:255.255.255.0,gw:10.0.0.1

	wifi_event_monitor_handle_event_cb is called
WiFi connection established
IP address: 10.0.0.61
pin,mode,pullup= 4 2 0
Pin data at mode: 4 60000838, 2 0 0, fffffffe
Function platform_gpio_mode() is called. pin_mux:1610614840, func:0
PANIC: unprotected error in call to Lua API (main.lua:8: attempt to index global 'mqtt' (a nil value))

**Comment by mydakota** [comment]
> = node.heap()
42464
> for k,v in pairs(file.list()) do l = string.format("%-15s",k) print(l.."   "..v.." bytes") end
functions.lua     1159 bytes
config.lua        305 bytes
main.lua          808 bytes
init.lua          592 bytes
> 
> = gpio.read(4 G)
stdin:1: ')' expected near 'G'
> = gpio.read(4 G)
stdin:1: ')' expected near 'G'
> = gpio.read(4 G)
stdin:1: ')' expected near 'G'
> = gpio.read(4 G)
stdin:1: ')' expected near 'G'
> = gpio.read(4 G)
stdin:1: ')' expected near 'G'
> gpio.mode(4 G,gpio.INPUT,gpio.FLOAT)
stdin:1: ')' expected near 'G'
> = gpio.read(4 G)
stdin:1: ')' expected near 'G'
> = gpio.read(4 G)
stdin:1: ')' expected near 'G'
> 

getting pings through home assistant now so mqtt is now working as it was missing from the firmware but now this grrrrrr

**Comment by mydakota** [comment]
gpio.read(0)
0= gpio.read(0)
0= gpio.read(0)
0= gpio.read(0)
0= gpio.read(0)
0= gpio.read(0)
0= gpio.read(0)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0/ping/ : ESP826611685042
= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0/ping/ : ESP826611685042
= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0/ping/ : ESP826611685042
= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0= gpio.read(4)
0

> uart.setup(0,9600,8,0,1,1)
> gpio.mode(4,gpio.INPUT,gpio.FLOAT)
> /ping/ : ESP826611685042
gpio.mode(4,gpio.INPUT,gpio.PULLUP)
> = gpio.read(4)
1
> uart.setup(0,9600,8,0,1,0)
Monitoring GPIO2: 

11/ping/ : ESP826611685042
1100101111/ping/ : ESP826611685042
10001111
1
> > > /ping/ : ESP826611685042

**Comment by mydakota** [comment]
ok i can get the pin to change states now and send data to mqtt then home assistant OK
the issue is the pin will switch one way with a negative contact the the only way to reset it is to use a positive wire and it changes back this should automatically change from high to low 
any Ideas why this will not function correctly 

/sensor/garage/ : ESP826611685042 - {"mac":"5c:cf:7f:b2:4c:b2", "ip":"10.0.0.61","state":"0"}
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/sensor/garage/ : ESP826611685042 - {"mac":"5c:cf:7f:b2:4c:b2", "ip":"10.0.0.61","state":"1"}
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/ping/ : ESP826611685042
/sensor/garage/ : ESP826611685042 - {"mac":"5c:cf:7f:b2:4c:b2", "ip":"10.0.0.61","state":"0"}
/ping/ : ESP826611685042

**Comment by FigJam23** [comment]
why does it spit out ip mac and rest of details home assistant hates this how can i fix please
g/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/sensor/garage/ : ESP8266-11685042 - {"mac":"5c:cf:7f:b2:4c:b2", "ip":"10.0.0.61","state":"0"}
/sensor/garage/ : ESP8266-11685042 - {"mac":"5c:cf:7f:b2:4c:b2", "ip":"10.0.0.61","state":"0"}
/sensor/garage/ : ESP8266-11685042 - {"mac":"5c:cf:7f:b2:4c:b2", "ip":"10.0.0.61","state":"0"}
/sensor/garage/ : ESP8266-11685042 - {"mac":"5c:cf:7f:b2:4c:b2", "ip":"10.0.0.61","state":"0"}
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
= gpio.read(4 G)
stdin:1: ')' expected near 'G'
> /ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042
/ping/ : ESP8266-11685042

**Comment by Wifsimster** [comment]
Ok, sorry for the delay, i'll try to look into it in the next days or so :)
I'll probably rewrite the code, to be compliant with my other project Overwatch : https://github.com/Wifsimster/overwatch

**Comment by Wifsimster** [comment]
Ok i update my code with an all new version. I'll test it soon.

For the logs in your console, it's the `print()` function, just comment all the logs by adding `--print()`

However, i don't think your issue it's related to the original code. Keep me in touche with the new version if you still have not figure it out :)

**Comment by FigJam23** [comment]
Thank you for updating you code much appreciated and thank you for sharing your work. Once I get a chance I'll have another go at it :)

Sent from my iPhone

On 28 Jun 2017, at 5:19 pm, Wifsimster <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok i update my code with a all new version. I'll test it soon.

For the logs in your console, it's the print() function, just comment all the logs by adding --print()

However, i don't think your issue it's related to the original code. Keep me in touche with the new version if you still have not figure it out :)

**Comment by FigJam23** [comment]
Any chance of adding MQTT user name and password options as i use password could not see any location to enter these details under config.lua thanks

**Comment by Wifsimster** [comment]
You can add your username and password in [mail.lua](https://github.com/Wifsimster/pir-mqtt/blob/master/main.lua#L8) :

```lua
m = mqtt.Client(CLIENT_ID, 120, USERNAME, PASSWORD)
```

And add the two variables in config.lua :

```lua
USERNAME = "your_mqtt_username" 
PASSWORD = "your_mqtt_password"
```

For more info, see the [NodeMCU documentation](https://nodemcu.readthedocs.io/en/master/en/modules/mqtt/) :)

I just commit the changes : 5186eea0073c8bfeea897e285229444454fe412a
